#pragma once


enum ObjType { OBJ = 10000, OBSTACLE, REAR_OBSTACLE, PLAYER, BUBBLE, NPC, ITEM, PANNEL, TEXT };
enum ITEM_TYPE { BANANA = 0, SKULL, GEM, CAKE, CROSS};
enum NPC_TYPE { STAGE1_NPC };

enum SCENE_ID { NOTHING = 11000, INTRO, MENU, MENU_HELP, GAME_OVER, GAME_EXIT, STAGE1, STAGE2, STAGE3, STAGE4, STAGE5, BOSS};
enum MENUTYPE { NORMAL = 1, GAME_START, REPLAY, RANKING, HELP, MENU_EXIT };

enum ACTION { MOVE_LEFT = 0, MOVE_RIGHT, JUMP_LEFT, JUMP_RIGHT };
enum MOVE_ACTION { LEFT, RIGHT, UP, DOWN };
