#pragma once


enum ObjType { OBJ = 10000, PLAYER, PLAYER_BUBBLE, NPC, ITEM, PANNEL, TEXT };
enum SCENE_ID { NOTHING = 11000, INTRO, MENU, GAME_EXIT, STAGE1, STAGE2, STAGE3, STAGE4, STAGE5, BOSS, END};
enum MENUTYPE { NORMAL = 1, GAME_START, REPLAY, RANKING, HELP, MENU_EXIT };